import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import path from 'path'
import { copy } from 'esbuild-plugin-copy'
import sveltePlugin from 'esbuild-svelte'
import sveltePreprocess from 'svelte-preprocess'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

esbuild
  .build({
    banner: {
      js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
      'obsidian',
      'electron',
      '@codemirror/autocomplete',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      ...builtins,
    ],
    format: 'cjs',
    watch: !prod,
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: path.join('./dist', 'main.js'),
    plugins: [
      sveltePlugin({
        compilerOptions: {
          css: true,
        },
        preprocess: sveltePreprocess(),
      }),
      copy({
        assets: {
          from: ['./assets/styles.css', 'manifest.json'],
          to: ['./'],
        },
      }),
    ],
  })
  .catch(() => process.exit(1))
